server:
  port: 8080
  servlet:
    context-path: /api/v1

spring:
  application:
    name: pos-backend

  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/pos_system_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
    username: ${DB_USERNAME:posuser}
    password: ${DB_PASSWORD:pospassword}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  # Redis Configuration
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  cache:
    type: ${CACHE_TYPE:simple}
    redis:
      time-to-live: 600000 # 10 minutes cache expiration

  # File upload configuration
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 5MB

# JWT Secrets Configuration
app:
  jwt:
    secret: ${JWT_SECRET:5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437} # Default secret key
    expiration-ms: 86400000 # 1 day expiration
    refresh-expiration-ms: 604800000 # 7 days expiration

# Springdoc OpenAPI Config (Swagger)
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
